server:
  port: 8082
spring:
  application:
    name: rpc-rmb-demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: default
    url: jdbc:mysql://localhost:3306/gk_rmb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
dubbo:
  scan:
    base-packages: com.alex.rmb
  protocol:
    name: dubbo
    port: 20211
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
hmily:
  ribbon:
    rule:
      enabled: true