
spring:
  application:
    name: rpc-rmb-demo
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  scan:
    base-packages: com.alex.rmb
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181