server:
  port: 8080
spring:
  application:
    name: kafka-demo
  kafka:
    bootstrap-servers: http://192.168.200.5:19090,http://192.168.200.5:19091,http://192.168.200.5:19092
    producer:
      auto-commit-interval: 20000
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ideal-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer