server:
  port: 8081
mybatis:
  mapper-locations: com/alex/dollar/mapper/*.xml
spring:
  application:
    name: rpc-dollar-demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: default
    url: jdbc:mysql://localhost:3306/gk_dollar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'

dubbo:
  scan:
    base-packages: com.alex.dollar
  protocol:
    name: dubbo
    port: 20212
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
hmily:
  ribbon:
    rule:
      enabled: true