server:
  port: 8080
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/gk_order_0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/gk_order_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        order:
          actualDataNodes: ds${0..1}.order_${0..15}
          tableStrategy:
            standard:
              shardingColumn: id
              shardingAlgorithmName: order_inline
          keyGenerateStrategy:
            column: id
            keyGeneratorName: snowflake
        defaultDatabaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database_inline

        shardingAlgorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: ds${user_id % 2}
          order_inline:
            type: INLINE
            props:
              algorithm-expression: order_${id % 16}

        keyGenerators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
      props:
        sql:
          show: true