server:
  port: 8080
mybatis:
  mapper-locations: com/alex/demo/mapper/*.xml
spring:
  application:
    name: redis-demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: default
    url: jdbc:mysql://localhost:3306/gk_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  redis:
    host: 127.0.0.1
    port: 6379
    auth: